version: "3.6"
services:
  mongo:
    container_name: mongo
    image: mongo
    ports:
      - 27017:27017
  postgres:
    image: postgres
    restart: unless-stopped
  mysql:
    image: mysql
volumes:
  mysql_data: {}
  api_data: {}

      
